### ISSUE TITLE
Check that everything is working OK with Docker and Client

### ISSUE THREAD

**Issue by davclark** [gigantum/gigantum-desktop#20]
At least on windows, we need to make sure Docker is running properly. This may not be entirely possible from the perspective of the desktop app, but should be part of the scoping process for this, see gigantum/gigantum-client#147.

Things that might not be working properly (the first two of which should be fixed by a Docker reboot :fingers-crossed:, or maybe even by a client reboot):

- Unable to write to a bind-mount
- Unable to run a docker build
- Unable to check out specified base-images repo

These would manifest in various problems depending on actions (e.g., publishing, modifying environment, creating a new project, etc.), or maybe the Client doesn't work at all.

Initially, this can be done manually. Once that's working OK, we might consider a heartbeat style check.

We may also roll #19 into a health check (though some of the image / storage management relevant to #19 should probably be separate).

**Comment by dkleissa** [comment]
One possible way to test docker better than just the API saying it's OK (which apparently isn't enough sometimes) would be to spin up a busybox container that bind mounts something and just runs `/bin/true` or something like that.

**Comment by davclark** [comment]
As mentioned in the just-written, high-priority https://github.com/gigantum/gigantum-cli/issues/47, there's a concern that we need to give the API more time to come up.

**Comment by dkleissa** [comment]
@davclark - I these checks are probably best implemented via both client updates and desktop/cli updates.

> Unable to write to a bind-mount
This is checked in the CLI already by looking for the logfile. Need to verify this is the same in the desktop app. also is that enough?

> Unable to run a docker build
What situation is this that we're not catching? like how do you get to where docker won't build, but you were able to start the client container? 

> Unable to check out specified base-images repo
I think the larger task is actually moving base-image repo updating to the background (along with some of the other startup stuff). We should then write state into redis, which can be used by the API to know if something failed and also if the application is ready to allow someone to create a new project.

**Comment by davclark** [comment]
Hmm.. well I wrote this in October and I realize I should've provided more detail. But I'm pretty sure some of this was driven by weird windows issues. So, for whatever reason, you could run an existing container (or maybe image) but not build. Restarting Docker would fix many of these issues.

That could actually be something that is handled by the front end in the client... suggesting (at least on Windows) to reset Docker if certain issues occur. But this particular issue hasn't happened for a while, so we could ignore that bullet.

**Comment by dkleissa** [comment]
I think this can probably be closed in favor of:

https://github.com/gigantum/gigantum-desktop/issues/29
https://github.com/gigantum/gigantum-client/issues/638
https://github.com/gigantum/gigantum-client/issues/457
