### ISSUE TITLE
More verbose description

### ISSUE THREAD

**Issue by probonopd** [gigantum/gigantum-desktop#25]
https://github.com/gigantum/gigantum-desktop/blob/f851ddd28ef8a06b178639f726dd4b02f3a441b3/package.json#L5

Please describe what Gigantum does.

This carries trough to places like https://appimage.github.io/Gigantum/.

**Comment by dkleissa** [comment]
@Mazharrr - Update the `description` entry in time for the next release to include a better description. Something like this is probably fine:

"A desktop application created using Electron to install and operate the Gigantum Client. Visit https://gigantum.com/download for more information"

**Comment by probonopd** [comment]
It is a music player? A payment system? No... it's

"Platform for developing, executing, and sharing analysis and computations, bundling data, code and environment into integrated repositories"
