### ISSUE TITLE
Add check for Docker disk space on client start

### ISSUE THREAD

**Issue by dkleissa** [gigantum/gigantum-desktop#29]
On startup, check for Docker disk space and make sure it is above 5GB. If below, warn the user and show link to docs for more information.

- [ ] Add check via running a container at start.
- [ ] If docker command fails, warn user to restart docker
- [ ] If space is below 5GB, warn user and link to docs. Allow them to choose to still start.
- [ ] If space is below 100MB, do now allow startup with warning and link to docs

**Comment by dkleissa** [comment]
After testing, this should be done via docker run command to check the root filesystem utilization inside a container.

**Comment by Mazharrr** [comment]
moving functionality into the client itself
