### ISSUE TITLE
Windows should not completely hide each other on gigantum desktop

### ISSUE THREAD

**Issue by calumbutler** [gigantum/gigantum-desktop#36]
**Describe the bug**
Currently, the position of all windows is identical. So, new windows completely hide others. This could be fixed with toast/modals, jittering window placement, or consolidating windows into a single actual window (and tabs, or simply changing contents depending on situtation)

**To Reproduce**
1. Start up gignatum desktop
2. Start up gigantum application
3. See error

**Environment (please complete the following information):**
 - OS: [All]

**Comment by dkleissa** [comment]
no longer applicable to new UI
