### ISSUE TITLE
Quitting Docker while Gigantum is Running

### ISSUE THREAD

**Issue by mgibbs1259** [gigantum/gigantum-desktop#69]
**Describe the bug**
Quitting Docker while Gigantum is running does not result in an error message indicating that I need to start Docker. 

**To Reproduce**
1. Start Gigantum desktop
2. Start a project container
3. Quit Docker
4. See that you get stuck on "Loading Please Wait..."

**Expected behavior**
I would expect a message to appear indicating that I need to start Docker. 

**Screenshots**
<img width="1680" alt="Screen Shot 2019-09-13 at 9 52 00 PM" src="https://user-images.githubusercontent.com/32986518/64902192-c61d4900-d670-11e9-9ebb-83081d23ca8e.png">

**Configuration**
 - OS: Mac
 - Version: 0.5.1

**Comment by Mazharrr** [comment]
Closing this, there is a ticket for gigantum-client to update the disconnect screen
