### ISSUE TITLE
Docker configurations not setting on Mac

### ISSUE THREAD

**Issue by Mazharrr** [gigantum/gigantum-desktop#88]
- There is an issue on mac where configuring docker during the install process does not change docker config settings

**Comment by mgibbs1259** [comment]
PASS
<img width="494" alt="Screen Shot 2019-12-13 at 3 18 00 PM" src="https://user-images.githubusercontent.com/32986518/70830315-f1bde580-1dbd-11ea-90e0-bf6a5330a9ce.png">
