### ISSUE TITLE
Make transition states more fluid

### ISSUE THREAD

**Issue by Mazharrr** [gigantum/gigantum-desktop#89]
- There is a delay when starting/stopping Gigantum (start/stop button). Make the button transition immediately and then revert to a confirmation message if needed

**Comment by mgibbs1259** [comment]
I believe that this is related, but not sure if it is worth writing a new ticket. After installing the desktop app, the client started, but opened to a blank page for localhost:10000 until refresh. However, this passes. The transitions are smooth between starting and stopping.
